[package]
name = "rust_pyaq"
version = "0.1.0"
authors = ["Yuji Ichikawa <ichikawa.yuji@gmail.com>"]

[dependencies]
getopts = "*"
rand = "*"
itertools = "*"

[target.'cfg(unix)'.dependencies]
tensorflow = { version = "*", features = ["tensorflow_unstable"] }

[target.'cfg(windows)'.dependencies]
tensorflow = { version = "*", features = ["tensorflow_unstable"] }

[features]
wasm = []

[lib]
name = "rust_pyaq_lib"

[[bin]]
name = "rust_pyaq"
path = "src/main.rs"

[[example]]
name = "rust_pyaq_wasm"
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = ["wasm"]
