[package]
name = "rust_pyaq"
version = "0.1.0"
authors = ["Yuji Ichikawa <ichikawa.yuji@gmail.com>"]

[dependencies]
getopts = "*"
rand = "*"
itertools = "*"
tensorflow = { version = "*", features = ["tensorflow_unstable"] }

[lib]
name = "rust_pyaq_lib"
path = "src/lib.rs"

[[bin]]
name = "rust_pyaq"
path = "src/main.rs"
